### ISSUE TITLE
Plug and Play

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/lepidopter#10]
Please make sure everything is plug and play. The operator shouldn't necessarily need to have a keyboard or monitor. Everything should be running smoothly as soon as it's powered up and plugged into ethernet.

**Comment by hellais** [comment]
I believe this is already the case @anadahz can you confirm?

**Comment by hellais** [comment]
@mrphs can you tag issues in the future?

**Comment by mrphs** [comment]
@hellais hmm sure... I just don't think I've the ability to do so. or if I do, I'm not sure how :)

**Comment by hellais** [comment]
You should now if you accept the invite to join the OONI group.

**Comment by anadahz** [comment]
Lepidopter already does this.
You can check all the relevant scheduled commands (cronjobs):
── cron.daily
│   │   │   ├── run_ooniprobe_deck
│   │   │   └── upload_reports
│   │   ├── cron.weekly
│   │   │   ├── remove_inc_reports
│   │   │   ├── update_deck
│   │   │   └── update_ooniprobe
Excerpt from: https://github.com/TheTorProject/lepidopter#lepidopter-repository-tree-structure
