### ISSUE TITLE
Ensure the image build script works on the latest version of ooniprobe

### ISSUE THREAD

**Issue by hellais** [TheTorProject/lepidopter#27]
Now that ooniprobe 1.4.2 is out we should ensure that the raspberry pi image is still working properly.

**Comment by anadahz** [comment]
@hellais I think this can be closed as ooniprobe 1.4.2 does works properly in Lepidopter.

**Comment by anadahz** [comment]
Some more tests were performed seem everything works as expected.
Feel free to re-open @hellais if you think that is not the case.
