### ISSUE TITLE
include wifi drivers for rpi 3

### ISSUE THREAD

**Issue by willscott** [TheTorProject/lepidopter#43]
currently, the only interface available on boot is eth0, even though the rpi 3 includes an on-board wifi chip

**Comment by willscott** [comment]
it looks like it may be trying to load the brcmfmac kernel module, but it appears to fail.

relevant demsg lines:

```
systemd[1]: Failed to start Load Kernel Modules
...
brcmfmac: brcmf_sdio_drivestrengthinit: No SDIO Drive strength init done for chip 43430 rev 1 pmurev 24
brcmfmac_sdio mmc1:0001:1: Direct firmware load for mrcm/mrcmfmac43430-sdio.bin failed with error -2
brcmfmac: brcmf_sdio_htclk: HT Avail timeout (10000000): clkctl 0x50
```

**Comment by anadahz** [comment]
I will try to add WiFi support in next release of lepidopter.
Thank you for reporting this.

**Comment by anadahz** [comment]
I need a Raspberry Pi 3 device to test this properly.

**Comment by willscott** [comment]
I'll bring one to you next week.

**Comment by anadahz** [comment]
@willscot excellent thanks!
