### ISSUE TITLE
Run the default deck as soon as the raspberry pi boots up

### ISSUE THREAD

**Issue by hellais** [TheTorProject/lepidopter#62]
It would greatly improve troubleshooting (as well as give us the ability to request people to power cycle the pi to recover from intermittend failures) if we were to run measurements as soon as the pi boots up.

Given the fact that we need to do some pre-configuration and testing on first boot, I would do this every other time that isn't the first boot (we can record the first boot inside of some file).

**Comment by anadahz** [comment]
This is currently supported in ooniprobe version 2.0.0 and no need to be implemented in lepidopter.
