### ISSUE TITLE
Add Lantern, Psiphon and OpenVPN test dependencies

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/lepidopter#65]
This task should add the dependencies needed to perform OONI measurements for Lantern, Psiphon and OpeVPN tests.

**Comment by anadahz** [comment]
Does it still make sense to add these dependencies to a newer release?

**Comment by hellais** [comment]
I think probably it makes sense to not do this at this time as we are going to use a different strategy for running the psiphon test (https://github.com/TheTorProject/ooni-probe/issues/744) that will probably also be similar for the Lantern test.
