### ISSUE TITLE
Wipe data from the micro-SD card after successful upload

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/lepidopter#8]
We should wipe data periodically right after a successful upload (assuming over .onion)
This help us to avoid running out of space on smaller SD cards and also avoid other security issues in the future.

**Comment by hellais** [comment]
I am also not 100% sure of this, but we can see what can be done (also not part of original requirements). Labels of github are :heart:

**Comment by anadahz** [comment]
This is the relevant [cronjob](https://github.com/TheTorProject/lepidopter/blob/master/lepidopter-fh/etc/cron.weekly/remove_inc_reports) to remove the successfully uploaded OONI reports.
