### ISSUE TITLE
Zip file for 0.3.5 is possibly corrupt and GPG sig is missing

### ISSUE THREAD

**Issue by hellais** [TheTorProject/lepidopter#88]
The size of the zip file for the 0.3.5 image seems to be very small (80 MB vs 182 MB for the xz version) and the signature file 404s.

See:
https://get.ooni.torproject.org/lepidopter/lepidopter-v0.3.5-beta-armel.img.zip
https://get.ooni.torproject.org/lepidopter/lepidopter-v0.3.4-beta-armel.img.zip.asc

**Comment by anadahz** [comment]
Thanks for verifying that it has been fixed now.
