### ISSUE TITLE
The latest image doesn't fit on a 4GB card

### ISSUE THREAD

**Issue by hellais** [TheTorProject/lepidopter#92]
The current image doesn't actually fit on a 4GB SD card. If it's too big to fit entirely on a 4GB card and burning it to 4GB you end up with a corrupt image.

**Comment by anadahz** [comment]
Did this occured on a specific SD card model/brand?

**Comment by hellais** [comment]
It may have been an issue with that specific brand and model, because I didn't experience this problem again with Kingston cards.

I am closing this.

**Comment by mrphs** [comment]
What brand was this? It might be worth adding a note in the installation
documents about it so people don't use that card.
